"""init

Revision ID: c9b0122a16d
Revises: None
Create Date: 2014-12-09 13:26:04.799675

"""

# revision identifiers, used by Alembic.
revision = 'c9b0122a16d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auth',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('account', sa.String(64), nullable=False, unique=True),
        sa.Column('pw_hash', sa.String(64), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.sql.false()),
        sa.Column('date_created', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.current_timestamp())
    )
    op.create_table(
        'order',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('custom_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(64), nullable=False, index=True, default='launch'),
        sa.Column('date_created', sa.DateTime(timezone=True), nullable=False, index=True,
                  server_default=sa.func.current_timestamp()),
        sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False, index=True,
                  server_default=sa.func.current_timestamp())
        )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    op.drop_table('order')
    ### end Alembic commands ###
