"""init

Revision ID: c9b0122a16d
Revises: None
Create Date: 2014-12-09 13:26:04.799675

"""

# revision identifiers, used by Alembic.
revision = 'c9b0122a16d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
